Repository co-log/co-log, pull requests merged in 2022-02, with the labels that each got.

#226 Support custom formatting - especially allow easy TZ support 😄
  .github/workflows/ci.yml
  co-log/co-log.cabal
  co-log/src/Colog/Message.hs
  stack.yaml
Labels: enhancement, refactoring

#229 Split co-log from others
  .travis.yml
  CHANGELOG.md
  README-2.md
  README.lhs
  appveyor.yml
  cabal.project
  co-log-benchmark/CHANGELOG.md
  co-log-benchmark/LICENSE
  co-log-benchmark/Main.hs
  co-log-benchmark/Setup.hs
  co-log-benchmark/co-log-benchmark.cabal
  co-log-core/CHANGELOG.md
  co-log-core/LICENSE
  co-log-core/README.md
  co-log-core/co-log-core.cabal
  co-log-core/src/Colog/Core.hs
  co-log-core/src/Colog/Core/Action.hs
  co-log-core/src/Colog/Core/Class.hs
  co-log-core/src/Colog/Core/IO.hs
  co-log-core/src/Colog/Core/Severity.hs
  co-log-core/test/Doctests.hs
  co-log-polysemy/CHANGELOG.md
  co-log-polysemy/LICENSE
  co-log-polysemy/README.md
  co-log-polysemy/co-log-polysemy.cabal
  co-log-polysemy/example/Main.hs
  co-log-polysemy/src/Colog/Polysemy.hs
  co-log-polysemy/src/Colog/Polysemy/Effect.hs
  co-log.cabal
  co-log/LICENSE
  co-log/README.lhs
  src/Colog.hs
  src/Colog/Actions.hs
  src/Colog/Concurrent.hs
  src/Colog/Concurrent/Internal.hs
  src/Colog/Contra.hs
  src/Colog/Message.hs
  src/Colog/Monad.hs
  src/Colog/Pure.hs
  src/Colog/Rotation.hs
  test/Doctest.hs
  test/Property.hs
  tutorials/1-intro/Intro.lhs
  tutorials/1-intro/Intro.md
  tutorials/2-custom/Custom.lhs
  tutorials/2-custom/Custom.md
  tutorials/Concurrent.hs
  tutorials/Main.hs
  tutorials/README.md
Labels: refactoring

#232 [#231] Combine READMEs for co-log
  README-2.md
  README.lhs
  README.md
Labels: doc

#233 [#187] Move 'Colog.Concurrent' into separate package 'co-log-concurrent'
  CHANGELOG.md
  co-log.cabal
  src/Colog.hs
  src/Colog/Concurrent.hs
  src/Colog/Concurrent/Internal.hs
  tutorials/Concurrent.hs
Labels: enhancement, package:co-log, refactoring

#234 [#189] Add OSX check on CI
  .github/dependabot.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  cabal.project
  co-log.cabal
  src/Colog/Actions.hs
  src/Colog/Message.hs
  src/Colog/Pure.hs
  stack.yaml
  test/Property.hs
  tutorials/Concurrent.hs
  tutorials/Main.hs
Labels: CI
